name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the base environment

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Debug: Output ECR repository URI to ensure it's correct
    - name: Debug ECR URI
      run: echo "ECR URI: ${{ secrets.ECR_REPOSITORY_URI }}"

    # Step 4: Log in to AWS ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true

    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -f ./Dockerfile -t ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }} .

    # Step 6: Push Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}

    # Step 7: Log out from Docker (optional)
    - name: Logout from Docker
      run: docker logout
